IMAGE_NAME="pmjs-linux"
IMAGE_VERSION="0.1.0"

OUTPUT_DIR="./output"
LOG_DIR="./logs"

ROOTFS_FILENAME="auto"
HOMEFS_FILENAME="auto"

SOURCE_ROOT="auto"
HOME_SOURCE="auto"
HOME_USER="usuario"

IMAGE_COMPRESSION="zstd"
ZSTD_LEVEL=3

MIN_FREE_SPACE_GIB=8
HOMEFS_MAX_SIZE_MIB=512
